# KallistiOS ##version##
#
# addons/libkosgcov/Makefile
# Copyright (C) 2026 Andress Barajas
#

TARGET = libkosgcov.a
OBJS = kos_gcov.o
KOS_GCCVER_MIN = 12.0.0

include $(KOS_BASE)/addons/Makefile.prefab
